#define STLINK_CMD_READSERN					0xF1
#define STLINK_CMD_0XF2							0xF2
#define STLINK_CMD_0XF3							0xF3
#define STLINK_CMD_SWIM							0xF4
#define STLINK_CMD_0XF5							0xF5

#define STLINK_SUBCMD_INIT					0x00
#define STLINK_SUBCMD_FINI					0x01
#define STLINK_SUBCMD_0X02					0x02
#define STLINK_SUBCMD_SPEED					0x03
#define STLINK_SUBCMD_SWIM_ENTRY		0x04
#define STLINK_SUBCMD_SWIM_SRST			0x05
#define STLINK_SUBCMD_SWIM_SYNC			0x06
#define STLINK_SUBCMD_RESET_ON			0x07
#define STLINK_SUBCMD_RESET_OFF			0x08
#define STLINK_SUBCMD_POLL					0x09
#define STLINK_SUBCMD_SWIM_WOTF			0x0A
#define STLINK_SUBCMD_SWIM_ROTF			0x0B
#define STLINK_SUBCMD_GET_RESULT		0x0C
#define STLINK_SUBCMD_GET_BUFSIZE		0x0D

#define STLINK_STATE_READY					0x00
#define STLINK_STATE_BUSY						0x01
#define STLINK_STATE_TIMEOUT				0x04
#define STLINK_STATE_FAIL_ENTRY			0x09